### ISSUE TITLE
About your talk at Nodejs Global Summit

### ISSUE THREAD

**Issue by RafaelGSS** [Aschen/understand-js-runtimes#1]
Hey, nice talk!

1) How I can measure these improvements of Hidden Classes or recognize if my function is a hot path inside V8 Turbofan?

2) In typescript transpilation, all these rules (Hidden Classes, Inline cache) to make better performance of our application are worked on? Just saying... The order from object creation (hidden class) does matters?

**Comment by Aschen** [comment]
Hi @RafaelGSS ,

You can use the `--trace-opt` to get notified whenever Turbofan compile a function into optimized assembly code.
Also you can use `--trace-deopt` to know when a function optimized assembly can not be used anymore and a deopt is triggered to get back to bytecode

To measure those improvement you should apply them to you whole application and then use a benchmark tool like https://github.com/mcollina/autocannon or https://gatling.io/.

Another way is to try a micro-benchmark with this package: https://www.npmjs.com/package/benchmark
But be aware that there is many way to get falsy results with micro-benchmarks.


Since Typescript ensure same property order with classes and property initialization alongside with strong typing I think it will leverage most of v8 optimizations

You should be careful to initialize all properties in the constructor and to not use type union.
