### ISSUE TITLE
Inline Caching Internals of the Function

### ISSUE THREAD

**Issue by phillx** [Aschen/understand-js-runtimes#2]
Hello @Aschen,

I would like to know if you have some knowledge about caching internals related 
to function utilizing object destruction of argument?

```js
const payload = {
  subtotal: 10,
  tax: 2,
  name: "something",
  // ...
};

function superSecret({ subtotal, tax }){
 return subtotal + tax;
}

superSecret(payload);
```

Thanks for your presentation!

**Comment by Aschen** [comment]
Hello @phillx ,

Since Node.js 8, the destructuring assignment looks like syntactic sugar with similar performances.  
A micro-benchmark can assert this:

```
$ node bench/destruct.js
normal x 134,934,585 ops/sec ±0.91% (89 runs sampled)
destruct x 134,226,564 ops/sec ±0.80% (92 runs sampled)
Node.js v12.16.3
V8 v7.8.279.23-node.35
Fastest is normal,destruct
```

<details><summary>benchmark code</summary>

```
'use strict'

var benchmark = require('benchmark')
var suite = new benchmark.Suite()

const payload = {
  subtotal: 10,
  tax: 2,
  name: "something",
  // ...
};

function normal(payload) {
  return payload.subtotal + payload.tax;
}

function destruct({ subtotal, tax }) {
  return subtotal + tax;
}

let i = 0
suite.add('normal', function polymorphic() {
  i = normal(payload)
})

suite.add('destruct', function polymorphic() {
  i = destruct(payload)
})

.on('cycle', function(event) {
  console.log(String(event.target));
})

.on('complete', function() {
  console.log('Node.js v' + process.versions.node);
  console.log('V8 v' + process.versions.v8);
  console.log('Fastest is ' + this.filter('fastest').map('name'));
})

suite.run()
```

</details>

First I was thinking that v8 create an intermediary object with the destructured properties and then give it to your function but by investigating I found out that destructuring it's really just syntactic sugar on local variable name.

The easiest way to know if your function receive the same shape with destructuring is to run this snippet with the `--trace-opt` and `--trace-deopt` options. If my first thought was correct then calling the method with the original payload and with an object containing only `subtotal` and `tax` should be the same.

But by running this snippet you can see that v8 is actually triggering a deopt.

```js
const payload = {
  subtotal: 10,
  name: 'toto',
  tax: 2,
};

function superSecret({ subtotal, tax }) {
  return subtotal + tax;
}

// trigger hot path compilation
for (let i = 100000; i--; ) {
  superSecret(payload);
}

const payload2 = {
  subtotal: 21,
  tax: 42
};

// this trigger a deopt
superSecret(payload2)
```

```
$ d8 --trace-opt --trace-deopt example.js
[...]
[compiling method 0x2092f8e5fa61 <JSFunction superSecret (sfi = 0x2092f8e5f701)> using TurboFan]
[...]
[deoptimizing (DEOPT eager): begin 0x2092f8e5fa61 <JSFunction superSecret (sfi = 0x2092f8e5f701)> (opt #0) @1, FP to SP delta: 24, caller sp: 0x7ffc8151be80]
            ;;; deoptimize at <test-js.js:11:24>, wrong map
```

So we can conclude that using the destructuring assignment is the same as passing the whole object to the function so you have to take care of passing objects with the same shapes if you want to benefits from v8 optimizations on in-line cache an JIT
